apiVersion: troubleshoot.replicated.com/v1beta1
kind: Collector
metadata:
  name: collector-sample
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - logs:
        collectorName: grafana-logs
        name: grafana/logs
        selector:
          - app=grafana
    - logs:
        collectorName: redis-logs
        name: redis/logs
        selector:
          - app=redis
