apiVersion: velero.io/v1
kind: Backup
metadata:
  name: backup
spec:
  hooks:
    resources:
    - name: echo-hook
      includedResources:
      - 'pods'
      labelSelector:
        matchLabels:
          app: postgres
          component: nginx
      pre:
      - exec:
          container: nginx
          command: ["/bin/bash", "-c", "echo $(date) > /scratch/timestamp"]
      - exec:
          container: nginx
          command: ["/bin/bash", "-c", "head -c 100M </dev/urandom >/scratch/data"]
          timeout: 3m
          onError: Continue
    - name: postgres-hook
      includedResources:
      - 'pods'
      labelSelector:
        matchLabels:
          app: postgres
          component: nginx
      pre:
      - exec:
          container: postgresql
          command: ["/bin/bash", "-c", "echo $(date) > /scratch/timestamp"]
      - exec:
          container: postgresql
          command: ["/bin/bash", "-c", 'export PGPASSWORD={{repl ConfigOption "postgres_password"}} && pg_dump -U postgres -d my-database -h postgresql > /scratch/backup.sql']
          timeout: 3m
          onError: Continue
