apiVersion: velero.io/v1
kind: Backup
metadata:
  name: backup
  # Snapshot capabilities only enabled for embedded databases
  kots.io/when: '{{repl ConfigOptionEquals "postgres_type" "embedded_postgres" }}'
spec:
  hooks:
    resources:
    - name: postgres-hook
      includedResources:
      - 'pods'
      labelSelector:
        matchLabels:
          app: pg-snapshot
      pre:
      - exec:
          command: ["/bin/bash", "-c", "echo $(date) > /scratch/timestamp"]
      - exec:
          # Inject the postgres password into the environment and perform a pg-dump
          command: ["/bin/bash", "-c", 'export PGPASSWORD=$DB_PASSWORD && pg_dump -U $DB_USER -d $DB_NAME  -h $DB_HOST > /scratch/backup.sql']
          timeout: 3m
          onError: Continue
