apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: config-postgres
spec:
  groups:
    - name: postgres_settings
      description: Configuration to serve as an example for creating your own. See [https://kots.io/reference/v1beta1/config/](https://kots.io/reference/v1beta1/config/) for configuration docs. In this case, we provide example fields for configuring an Ingress object.
      items:
        - name: postgres_password
          title: Postgres Password
          type: text
          default: "secretpassword"
        - name: application_namespace
          title: Application Namespace
          type: text
          default: "kotsapp"
