apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-nginx
  labels:
    app: postgres
    component: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      component: nginx
  template:
    metadata:
      labels:
        app: postgres
        component: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          envFrom:
          resources:
            limits:
              memory: '256Mi'
              cpu: '500m'
