apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: postgres-snapshots
spec:
  title: Postgres Snapshots
  icon: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/color/kubernetes-icon-color.png
  statusInformers:
    - deployment/pg-consumer
    - deployment/pg-snapshot

