---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: mongodb-enterprise-demo
spec:
  title: Mongo Operator OM Helm
  icon: https://github.com/mongodb-js/favicon/raw/master/favicon.ico
  additionalImages:
    - quay.io/mongodb/mongodb-enterprise-database:1.4.2
    - quay.io/mongodb/mongodb-enterprise-operator:1.4.2

