apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-application-ingress-http
  annotations:
    kots.io/exclude: 'repl{{ or (ConfigOptionEquals "builtin_ingress" "1" | not) (ConfigOptionEquals "require_ssl" "1") }}'
    kots.io/placeholder: repl{{ printf "'true'" }}repl{{ ConfigOption "annotations" | nindent 4 }}
spec:
  rules:
  - http:
      paths:
      - path: /nginx
        backend:
          serviceName: nginx-app
          servicePort: 80
      - path: /
        backend:
          serviceName: kotsadm
          servicePort: 3000