apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress-http
  annotations:
    kots.io/exclude: 'repl{{ or (ConfigOptionEquals "builtin_ingress" "1" | not) (ConfigOptionEquals "require_ssl" "1" | not) }}'
    kots.io/placeholder: repl{{ printf "'true'" }}repl{{ ConfigOption "annotations" | nindent 4 }}
spec:
  backend:
    serviceName: nginx-app
    servicePort: 80
  tls:
    - hosts:
        - repl{{ ConfigOption "hostname" }}
      secretName: kotsadm-tls
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: nginx-app
          servicePort: http

