apiVersion: apps/v1
kind: Deployment
metadata:
  name: kurl-proxy
  labels:
    app: kurl-proxy
spec:
  selector:
    matchLabels:
      app: kurl-proxy
  template:
    metadata:
      labels:
        app: kurl-proxy
    spec:
      containers:
      - name: proxy
        image: kurl/proxy
        env:
        - name: NODE_PORT
          value: "30880"
        - name: UPSTREAM_ORIGIN
          value: http://kotsadm:3000
        - name: TLS_SECRET_NAME
          value: kotsadm-tls
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: kotsadm-config
          mountPath: /etc/kotsadm
      serviceAccount: kurl-proxy
      volumes:
      - name: kotsadm-config
        configMap:
          name: kotsadm-application-metadata
          optional: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kurl-proxy
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: secret-manager
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "list", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kurl-proxy-tls-secrets
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-manager
subjects:
- kind: ServiceAccount
  name: kurl-proxy
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: kurl-proxy
spec:
  type: NodePort
  selector:
    app: kurl-proxy
  ports:
  - port: 8800
    targetPort: 8800
    nodePort: 30880