name: nginx-ingress CI

on:
  push:
    paths:
    - 'nginx-ingress/**'
    branches:
      - stable
      - unstable
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create a release on Channel associated with the branch
      run: make release
      env:
        REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
        REPLICATED_APP: nginx-ingress



